name = "pip3queak/session07activities"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'pip3queak/session07activities'"

[repository]
user = "Pip3queak"
project = "session07activities"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
